### ISSUE TITLE
[BUG]: Content in "About Us" section not visible in light mode

### ISSUE THREAD

**Issue by Asthasingh-2002** [akshitagupta15june/PetMe#1017]
Description:
When using the application in light mode, the content in the "About Us" section is not visible. It seems that the text color is not appropriately set for light mode, making the content appear to be invisible.

Steps to Reproduce:

Open the application in light mode.
Navigate to the "About Us" section.

Expected Behavior:
The content in the "About Us" section should be clearly visible and legible, irrespective of the selected color mode.

**Screenshots**

https://github.com/akshitagupta15june/PetMe/assets/81636517/2948925a-dcce-4fe0-b864-c05cf352e315

Desktop 
 - OS: Window10
 - Browser: Chrome
 - Version: 115.0.5790.110

**Comment by emily883** [comment]
This issue was fixed

**Comment by victor-duarte** [comment]
@akshitagupta15june, I am not sure this is fixed.

If not fixed, please re-open and assigned to me so I can work on it.
My suggestion would be to match colors in the top header:

<img width="400" alt="image" src="https://github.com/akshitagupta15june/PetMe/assets/1746030/a7952fd7-fcc9-424c-b0a0-3388b3a9b2ea">

### Secondary task(s)
Remove hover on About Us title since this element is not a CTA. (image showing hover effect):

<img width="400" alt="image" src="https://github.com/akshitagupta15june/PetMe/assets/1746030/943ad3bb-82a3-43d2-9c6a-3d47275c7bf3">
