### ISSUE TITLE
Important : Petme

### ISSUE THREAD

**Issue by Susmita-Dey** [akshitagupta15june/PetMe#178]
**Is your feature request related to a problem? Please describe.**
Yes, contributors are directly making PRs without creating issues and getting assigned.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/79099734/194055404-d3908240-450d-43b4-922b-a0a54fc55d85.png)

Add a line here in bold and italic format so that contributors would note the following line before making any contributions - **"DONT CREATE PRs WITHOUT CREATING ISSUE AND GETTING ASSIGNED"**

**Describe alternatives you've considered**
Null

**Comment by akshitagupta15june** [comment]
I am pinning this issue as important

**Comment by shubhamrawat090** [comment]
Hey @Susmita-Dey can you assign it to me?

**Comment by Susmita-Dey** [comment]
@shubhamrawat090 Go ahead

**Comment by shubhamrawat090** [comment]
@Susmita-Dey I have done it and made a pull request. Please check it.

**Comment by Huluvu424242** [comment]
> I am pinning this issue as important

Hi, 
is this a good thing? In my mind it isn't because:

1. There is an issue maybe number 1 
1. There is an developer maybe A with comment "assign me, please ..."
1. There is an developer maybe B with comment "assign me, please ..."
1. You assign today to A but no PR is opened to solve the problem
1. You assign in two weeks to B but no PR is opened to solve the problem
1. C has no comment "assign me, please ..." and go ahead looking into the next projekt but C could solve the problem in 5 minutes. I think this is not a good workflow. 

I think important is: each PR must be an description which describe which problem will be solved. I think, it is no problem to have many PRs which solve the same problem but it is an problem to have issues without solving PRs.
