### ISSUE TITLE
Add a toggle switch for dark view and bright view in website 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#31]

**Comment by Aragorn-64** [comment]
Hi @akshitagupta15june, I am learning/building my CSS skills and would like to take up the task of building a Dark theme as a part of Hacktoberfest. Can you assign this task to me?

**Comment by akshitagupta15june** [comment]
Can you work on both parts like the issue is about to toggle between both as currently the theme is dark

**Comment by akshitagupta15june** [comment]
You can also change the background of website if you want as if it's interfere with the theme change

**Comment by akshitagupta15june** [comment]
Assigning u

**Comment by Mustafa-Azad025** [comment]
Hello Sir,

I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me.

**Comment by akshitagupta15june** [comment]
@Mustafa-Azad025 can you look for other issue because this is already assigned to @Aragorn-64

**Comment by Aragorn-64** [comment]
Okay, I think I understand. I need to build a Light theme for the site and also create a toggler for switching between them, right?

**Comment by akshitagupta15june** [comment]
Yes

**Comment by Aragorn-64** [comment]
@akshitagupta15june 
This is the dark theme
![image](https://user-images.githubusercontent.com/72992475/193342794-56902281-27aa-42aa-9861-9047a5accd2f.png)
and this is the light theme
![image](https://user-images.githubusercontent.com/72992475/193342838-d96b543a-a54c-41af-b9c8-8dbf1681d49f.png)

This switches based on the Toggle in the navbar 

I implemented this using JS and it can be used for any elements in the future by simply adding the classes "text_1" "bg_1" etc as described in my JS file and the toggle will work.

If you are happy, I will submit a PR

**Comment by akshitagupta15june** [comment]
It's good but the eepo has been updated few hours before with new UI so can you fetch and merge for updating with current UI

**Comment by Aragorn-64** [comment]
Sure

**Comment by Aragorn-64** [comment]
@akshitagupta15june I feel that the CSS coding style used by the new contributions has changed too much ( and I feel that custom classes with specific styles go against the purpose of Tailwind .. which is about using Inline styles). My submission was with respect to the previous coding style. If you are fine with it, id like to submit my toggle theme and js code for the toggle (which is written so that it will be easier for future contributors to simply add a single class eg: "text_1" and it will make the text have a  default(dark theme) color of text-gray-900 and be switchable to text-slate-50 by the toggle. The exact colors can be changed at any time easily as well. Please let me know what you think

**Comment by Aragorn-64** [comment]
Okay @akshitagupta15june I am working on a revised method that will toggle to a dark color scheme on press and will revert to the current style (light) while taking current changes.

**Comment by akshitagupta15june** [comment]
yes! please take ur time @Aragorn-64
