### ISSUE TITLE
Title: Invisible text input in email form for subscription to the news letter

### ISSUE THREAD

**Issue by raslene5** [akshitagupta15june/PetMe#320]
**Description:**
On the PetMe website, when trying to fill in the email form in the "Subscribe to our newsletter" section, users experience a problem where the text they type is not visible on the screen. Instead, the text appears to be invisible until the user selects it with their cursor. This makes it difficult for users to see what they are typing and can cause confusion.

**To Reproduce**
1. Go to the PetMe website: 'https://akshitagupta15june.github.io/PetMe/index.html#'
2. Go to the "Subscribe to our newsletter" section.
3. Click on the email input form to type in your email address.
4. Observe that the text you type does not appear on the screen.
5. Select the text with your cursor to see what you have typed.

**Expected behavior**
When typing in the email input form, the text should be visible on the screen as it is being typed, allowing users to see what they are typing and correct any mistakes.

**Screenshots**
![b](https://user-images.githubusercontent.com/122980534/229350162-1ee8628d-693f-4f7f-870c-36e9576476ae.GIF)
![b1](https://user-images.githubusercontent.com/122980534/229350179-9d9d6b3f-323c-45ec-884d-5f44caf0a7b8.GIF)
i can fix it once i get assigned

**Comment by tangorishi** [comment]
So I guess this problem is not solve even after merging the referenced pull req. User is only able to see the entered email only on selecting the particular area in which the email is written.
Also there's another problem that is there is no way that user gets to know if they are subscribed to the newsletter or not. Because after clicking on the red subscribe button there's no appropriate message displayed or any sort of sign is given to know if the user is subscribed to the newsletter or not.
I am attaching the screenshots for reference.

![Screenshot (272)](https://user-images.githubusercontent.com/110519406/231001209-32ae7796-3570-4c20-8b30-b1bab90bb7bd.png)

![Screenshot (271)](https://user-images.githubusercontent.com/110519406/231001262-474ce676-1394-4509-bda0-065704841a0e.png)

**Comment by mud1tx** [comment]
@akshitagupta15june I can work on this issue, please assign it to me.

**Comment by anuza08** [comment]
hey, can you assign me this issue?

**Comment by yamadivya** [comment]
I am interested to contribute
