### ISSUE TITLE
[GSSoC'23] Fix: Pet News page center alignment 

### ISSUE THREAD

**Issue by davidkilamlya** [akshitagupta15june/PetMe#540]
Hello @akshitagupta15june am david from GSSOC'2023
We have to style our news page to look pretty and user familiar by aligning the content well centered  with card style version, includes all three major parts "Heading, image, descriptions" wrapped together in a single card.
can you assign this task to me?

**Comment by Aditi323** [comment]
Could you please assign me this as a GSSOC Contributor.

**Comment by Pv200** [comment]
hey @akshitagupta15june, i am Prakhar as a contributor in gssoc 23
I can solve the center alignment issue by converting the heading, image, description into the same div and then through 
by css3 i will convert it to flex and adjust text-alignment to center and then i will adjust its padding and margin so that it will look more beautiful. 

so please assign it to me 
Thank you in advance.
