### ISSUE TITLE
Add a support us section in the navbar -->volunteer.html

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#58]
on hovering support us a drop down will be there and "Become a Volunteer" option will be there and on clicking volunteer now that page will take to a volunteer.html 

currently leave that volunteer.html page as blank

**Comment by Anuran12** [comment]
Hi @akshitagupta15june can you please assign it to me?

**Comment by akshitagupta15june** [comment]
go for it @Anuran12

**Comment by Anuran12** [comment]
Hi @akshitagupta15june  I started working on this.. please wait for my PR

**Comment by akshitagupta15june** [comment]
Ok

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/193522750-398c7fb8-84c2-44cb-b06c-1bbdda443283.png)

@akshitagupta15june Is it okay ?

**Comment by akshitagupta15june** [comment]
the button is not needed for support us just on hovering it will have a dropdown and shift contact us after supports us

**Comment by Anuran12** [comment]
> the button is not needed for support us just on hovering it will have a dropdown and shift contact us after supports us

Ohh okay

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/193533303-96065127-a3ba-4a58-8268-48997dbe0832.png)
Hey @akshitagupta15june it's looking better if I add the "support us" link before the "SOS Report" link.

**Comment by Anuran12** [comment]
so can I create the PR now ?

**Comment by akshitagupta15june** [comment]
yes

**Comment by Anuran12** [comment]
Btw.. I have a out of topic question.. 

will you really use this web site for pet adoption ? I mean if it's yes then I would like to improve this website because I love pets too^_^. 

Actually I saw the codes in the repository and it's not looking good to me.. The codes are me messy, the dark mode light mode does not looking good. and this website need lots of improvements.

**Comment by Anuran12** [comment]
So if you use this website as a real life based project then I would like to help you @akshitagupta15june

**Comment by akshitagupta15june** [comment]
@Anuran12 i know currently the website is very messy, this website was created in a hackathon and won first prize and total it has 3 more members who contribute @Susmita-Dey @muditchoudhary and aisle 
So we just thought why not make this website connected with real world so thats why we added this to hacktoberfest so that many can contribute.
We are still working on it and improving codes daily.
Happy to have u as a contributor

**Comment by Anuran12** [comment]
> @Anuran12 i know currently the website is very messy, this website was created in a hackathon and won first prize and total it has 3 more members who contribute @Susmita-Dey @muditchoudhary and aisle So we just thought why not make this website connected with real world so thats why we added this to hacktoberfest so that many can contribute. We are still working on it and improving codes daily. Happy to have u as a contributor

Ohh wow that's great...  then I want to be a regular contributer for this website. but I don't know how because I am new in github. if you guide me I will try to contribute as much as possible even after hacktoberfest. 

I know Frontend quite well because i am learning it from class 11.. but never use my skill in opensource so yea this this my first time on github. yesterday I contributed into another repo 
https://www.limurl.ml/ 
(i made the dark mode feature)

Actually i am going to collage this year. that's why i thought i should start open source now. so if you guide me as a "didi" that would be very helpful .

**Comment by Anuran12** [comment]
> @Anuran12 u are always welcome to contribute @Susmita-Dey will also help u



> @Anuran12 u are always welcome to contribute @Susmita-Dey will also help u

Thanks didi

**Comment by Anuran12** [comment]
> @Anuran12 Check it out:- https://bio.link/susmitadey

okay... but what should I do ? should I follow you on twitter ?

**Comment by Susmita-Dey** [comment]
> okay... but what should I do ? should I follow you on twitter ?

You can do that. Also you can schedule a meeting using Calndly link if you need or dm me in socials.
