### ISSUE TITLE
Website logo improvement 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/PetMe#7]
New logo is also welcomed!

**Comment by CodeWAdi** [comment]
Hey there, firstly I want to appreciate you for the great work you are doing and I would be more than happy to help you in this project ,but I do wanna ask one thing will you please  merge this request after 1st of october so that this merge get counted in Hacktoberfest.

I have already started working on the logo making.

**Comment by akshitagupta15june** [comment]
Hey according to hacktoberfest you have to create pr after 1st oct to be counted so i would recommend you to work on that period only

**Comment by CodeWAdi** [comment]
Okay  may you please assign me this task i'll create a pr after create a logo

**Comment by akshitagupta15june** [comment]
Done

**Comment by akshitagupta15june** [comment]
Completed
